#!/bin/sh

set -e

# When running from GitLab, ensure imagePullSecret is available.
if [ -z "$GITLAB_CI" ]; then
  echo 'WARNING: This script should run from a GitLab CI runner' >&2
fi

if [ -z "$CI_REGISTRY" ]; then
  echo 'Error: Missing $CI_REGISTRY variable, is the container registry enabled?' >&2
  exit 1
fi

if [ -z "$KUBE_NAMESPACE" ]; then
  echo 'WARNING: Missing $KUBE_NAMESPACE variable, using default. Is Kubernetes integration enabled?' >&2
fi

SECRET_NAME="${1:-$CI_PROJECT_PATH_SLUG-registry}"
KUBE_NAMESPACE="${KUBE_NAMESPACE:-default}"
echo "Adding secret $SECRET_NAME..."

kubectl create secret -n $KUBE_NAMESPACE \
  docker-registry "$SECRET_NAME" \
  --docker-server="$CI_REGISTRY" \
  --docker-username="$CI_REGISTRY_USER" \
  --docker-password="$CI_REGISTRY_PASSWORD" \
  --docker-email="$GITLAB_USER_EMAIL" \
  -o yaml --dry-run | kubectl replace -n $KUBE_NAMESPACE --force -f -
