#!/bin/sh
# When running from GitLab, ensure imagePullSecret is available.
# This secret is only valid while the build job runs.

set -e

if [ -z "$GITLAB_CI" ]; then
  echo 'WARNING: This script should run from a GitLab CI runner' >&2
fi

if [ -z "$CI_REGISTRY" ]; then
  echo 'Error: Missing $CI_REGISTRY variable, is the container registry enabled?' >&2
  exit 1
fi

if [ -z "$KUBE_NAMESPACE" ]; then
  echo 'WARNING: Missing $KUBE_NAMESPACE variable, using default. Is Kubernetes integration enabled?' >&2
fi

SECRET_NAME="${1:-$CI_PROJECT_PATH_SLUG-registry}"
KUBE_NAMESPACE="${KUBE_NAMESPACE:-default}"
echo "Adding secret $SECRET_NAME..."

if [ "$(kubectl auth can-i get secrets -n $KUBE_NAMESPACE)" = "yes" ]; then
  APPLY_CMD="apply"
else
  APPLY_CMD="replace --force" # delete/create action, no get needed
fi

kubectl create secret -n $KUBE_NAMESPACE \
  docker-registry "$SECRET_NAME" \
  --docker-server="$CI_REGISTRY" \
  --docker-username="$CI_REGISTRY_USER" \
  --docker-password="$CI_REGISTRY_PASSWORD" \
  --docker-email="$GITLAB_USER_EMAIL" \
  -o yaml --dry-run | kubectl $APPLY_CMD -n $KUBE_NAMESPACE -f -
